### ISSUE TITLE
Possible new text check viewport resize not disabled

### ISSUE THREAD

**Issue by DavidMacDonald** [wet-boew/wet-boew-wpss#83] opened 2016-06-11 20:47 UTC
https://dequeuniversity.com/rules/axe/1.1/meta-viewport

**Comment by irwink** [comment] 2016-06-13 13:05
A check for meta name="viewport" and content with either "user-scalable=no" or "maximum-scale" less than 5.0 will be added.  Failures will be reported under success criterion 1.4.4 - Resize Text.

The check will be added in the next version of the tool.

Note: This is a duplicate of issue #78

**Comment by irwink** [comment] 2016-08-23 13:25
Check included in version 6.1.0

**Closed by irwink** 2016-08-23 13:25 UTC
